remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
logo: "_docs/assets/logo-256x256.png"

collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
  github:
    repo_link:
      enabled: true
    edit_link:
      enabled: true

gh_edit_link: true
gh_edit_view_mode: "edit"
