remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
logo: "assets/logo-256x256.png"

just_the_docs:
  github:
    repo_link:
      enabled: true
    edit_link:
      enabled: true

gh_edit_link: true
gh_edit_view_mode: "edit"
